# Generated by Django 3.1 on 2020-09-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200905_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fb_cpv', models.DecimalField(decimal_places=2, max_digits=3)),
                ('insta_cpv', models.DecimalField(decimal_places=2, max_digits=3)),
                ('twitter_cpv', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
